fight_data = {}
type_dict = {
	"normal": "Normal",
	"fighting": "Lucha",
	"flying": "Volador",
	"poison": "Veneno",
	"ground": "Tierra",
	"rock": "Roca",
	"bug": "Bicho",
	"ghost": "Fantasma",
	"steel": "Acero",
	"fire": "Fuego",
	"water": "Agua",
	"grass": "Planta",
	"electric": "Eléctrico",
	"psychic": "Psíquico",
	"ice": "Hielo",
	"dragon": "Dragón",
	"dark": "Siniestro",
	"fairy": "Hada",
	"lucha": "Fighting",
	"volador": "Flying",
	"veneno": "Poison",
	"tierra": "Ground",
	"roca": "Rock",
	"bicho": "Bug",
	"fantasma": "Ghost",
	"acero": "Steel",
	"fuego": "Fire",
	"agua": "Water",
	"planta": "Grass",
	"eléctrico": "Electric",
	"psíquico": "Psychic",
	"hielo": "Ice",
	"dragón": "Dragon",
	"siniestro": "Dark",
	"hada": "Fairy"
}
bot = None